### PR TITLE
Fix #68

### LINKED ISSUE #68: Sync crashes if the contentful output does not contain default locale data
Our output only contains `de_DE` data. That leads to the assertion `assert(mapping.count > 0, "Empty mapping for \(type)")` in `ContentfulSynchronizer.swift:165` in `create(_:fields:type:mapping)` to fail.

In the `create` methods the `ContentfulSynchronizer` calls `deriveMapping` with `foo.fields.keys`. `foo.fields` takes the fields set from the `localizedFields` map that's mapped to the "current locale", or the `defaultLocale` as fallback (see `Contentful/Assets.swift` or `Entry.swift`).

The "current locale" is saved on the json `NSDictionary` (`Client.swift:164`). But not as additional entry or anything, but using `objc_setAssociatedObject` (in `Decoding.swift`). When tried to be retrieved in `determineDefaultLocale` it's not there anymore.

The bug comes down to `Client.swift:166`:

```
(lldb) po (json as! NSDictionary).client
▿ Optional<Client>
  ▿ some : <Client: 0x6000000b9020>
```

```
(lldb) po ((json as! [String: Any]) as! NSDictionary).client
nil
```

p.s. personal opinion: `objc_setAssociatedObject` is almost _never_ a good idea and should be avoided.

### PR DESCRIPTION
**Pull request by sebastianludwig**
Fix by passing the Client object as `Map.context` instead of using `objc_setAssociatedObject`.

### CODE REVIEW

**Comment by loudmouth** [comment]
Looks great!

One added side-effect of your change is that the Objective-C runtime is no longer necessary to build the SDK which opens up nice possibilities for building on Linux in the future. Would you be able to remove the `import ObjectiveC.runtime` LOC at `Decoding.swift:11` and `SignalUtils.swift:11`?

**Comment by sebastianludwig** [comment]
Sure thing. Unfortunately my fix wasn't complete, I forgot to transfer the context in `SyncSpace.swift:195`. I'll update the PR.

However, in the meantime: Is `Client.space` assigned anywhere and I'm just too blind to find it? My fix is still not working and that's because `client.space` is always `nil`...

**Comment by loudmouth** [comment]
wowzas. I can't believe I never noticed that space was not being assiged. Updating the `fetchSpace` method to the following should do the trick:

```
    @discardableResult public func fetchSpace(then completion: @escaping ResultsHandler<Space>) -> URLSessionDataTask? {
        if let space = self.space {
            completion(.success(space))
            return nil
        }
        return fetch(url: self.URL()) { (result: Result<Space>) in
            self.space = result.value
            completion(result)
        }
    }
```

**Comment by loudmouth** [comment]
An added test asserting the the space is not nil on the client would be nice as well.

**Comment by sebastianludwig** [comment]
I've spent ~8h debugging and fixing and stretched the consent of my project manager already quite a bit, so I've to leave the test implementation to the paid employee ;-)

It turned out that the default locale fallback was a bit of a mess, too. BTW, maybe the `Defaults.` should be writeable?

This patch applied on your 0.4.1 release is working for us now. We still got issues with the unreleased 0.5.0, but we're going to ignore that for now.

**Comment by loudmouth** [comment]
Hey @sebastianludwig, it turns out locale handling was my next task even before your and your colleague opened these new issues yesterday and today.

I'm a bit confused as to how you'd like to proceed. Did you want to make the changes to the `fetchSpace` method and have this PR be merged? Or would you prefer that I work on top of your branch now. Either is fine for me.

**Comment by sebastianludwig** [comment]
Internally we're working with `sebastianludwig/contentful.swift/fix-0.4.1` and are happy with that. The identical patch applies to your current master, so I made it the target for this PR. If you're happy with it (except for the missing unit tests), I'd say let's merge it and you can continue your regular work and don't have any lingering PRs.

If you also want to fix the `0.4.1` release and push a `0.4.2` we'd be happy to switch back to the official version (maybe with an accompanying `contentful-persistence.swift` release? ;-)).

Before we switch to `0.5.0` we need to muster up some more debugging motivation.

**Comment by loudmouth** [comment]
Ok. If things are working on your end, I think it makes sense to merge this PR and then I'lll move forward with adding more tests and also continuing to improve logic around locales. I will also update contentful-persistence.swift as soon as the work on locales is done here and then ping you guys to do some testing. I think it will be too much work to fork a maintenance branch for the `0.4.x` releases and cherry pick patches, and I'd prefer to work on the head of the project.

If it's alright with you, I'll be tagging you both you and @tapwork in the changelog for the next release.

Merging this PR will automatically close the referenced issue #68. Is that ok?

**Pull request merged**
