### PR TITLE
Don't throw error if API error is not present in JSON

### LINKED ISSUE #71: Use optional initializers instead of throw
During development I use a "Swift Error" breakpoint. Contentful throws unnecessary exceptions while working totally fine. This is confusing and bad style. For example `ContentfulError` throws instead of returning `nil`. Optional initializers should be used instead.

### PR DESCRIPTION
**Pull request by loudmouth**
Fixes #71

### CODE REVIEW

**Comment by loudmouth** [comment]
@sebastianludwig you may want to cherry-pick this commit into your fork. I think it should solve your issue with the error breakpoint.

**Comment by tapwork** [comment]
@loudmouth thanks. can you release a new version of contentful.swift and ContentfulPersistenceSwift?

**Comment by loudmouth** [comment]
ContentfulPersistenceSwift needs some more work before it can be published. I'm not happy with all the anonymous closure argument names (i.e. `$0` etc) being used in important logic.

I'll be working on that repo next week. In the meantime, if you still have the maintainance branch that @sebastianludwig, my recommendation is just to cherry-pick this commit to make your life easier until I can publish updates. I'm working on improving locale handling in contentful.swift today.

**Comment by tapwork** [comment]
alright

**Pull request merged**
