### PR TITLE
Subsequent sync request bug fixed for given type

### PR DESCRIPTION
**Pull request by volkanbicer**
Hi,

Sync API is not able to subsequent requests for given content type, the problem is API is not expecting additional parameter alongside sync token.

### CODE REVIEW

**Comment by tomkowz** [comment]
@volkanbicer Thanks for reporting the issue. I tried to reproduce it and for me, it works fine. My steps to reproduce was:

1) Create a Content Model "word"
2) Enter 206 records

3) Create model "Word" in Core Data and create a corresponding class.
```
import Contentful
import ContentfulPersistence
import CoreData

final class Word: NSManagedObject, EntryPersistable {
    static var contentTypeId: ContentTypeId = "word"

    @NSManaged var id: String
    @NSManaged var localeCode: String?
    @NSManaged var createdAt: Date?
    @NSManaged var updatedAt: Date?

    @NSManaged var value: String

    static func fieldMapping() -> [FieldName : String] {
        return [
            "value": "value"
        ]
    }
}
```

4) Create simple `SyncSpace` class.
```
import Contentful
import ContentfulPersistence
import CoreData

final class SyncSpace: NSManagedObject, SyncSpacePersistable {
    @NSManaged var syncToken: String?
}
```

5) Set up the client.
```
    private func setup() {
        let spaceId = "9udmtmq3klnj"
        let accessToken = "QghA6Rja4xNLKWAvrXhZiEtE8XuazE8c4XLwrvwOT-8"

        let urlSessionConfiguration: URLSessionConfiguration = .default
        urlSessionConfiguration.httpAdditionalHeaders = [
            "Authorization": "Bearer \(accessToken)"
        ]

        let entryTypes: [EntryPersistable.Type] = [
            Word.self
        ]

        client = Client(spaceId: spaceId, accessToken: accessToken)

        store = CoreDataStore(context: managedObjectContext)
        let persistenceModel = PersistenceModel(
            spaceType: SyncSpace.self,
            assetType: Asset.self,
            entryTypes: entryTypes
        )

        syncManager = SynchronizationManager(
            client: client,
            localizationScheme: .all,
            persistenceStore: store,
            persistenceModel: persistenceModel
        )
    }
```

6) Perform a fetch operation which calls `Client.sync` multiple times (initial sync + next sync operations).
```
    private func performSyncWords() {
        syncManager.sync { [weak self] result in
            switch result {
            case .success(let space):
                guard let self = self else { return }

                print(space)
                do {
                    let words: [Word] = try self.store.fetchAll(type: Word.self, predicate: NSPredicate(value: true))
                    print(words.count)
                } catch {
                    print(error)
                }
            case .error(let error):
                print(error)
            }
        }
    }
```

7) Print number of received entries (206).

@volkanbicer Could you please let me know if this is still a valid issue on your side and if my steps matches yours? Make sure to use the newest version of the library. Thanks!

**Comment by tomkowz** [comment]
Closing this PR as it seems everything works in the framework.

**Comment by volkanbicer** [comment]
Hi @tomkowz , 

In my case, I have 205 entry for the specific type, 

```swift
let client = Client(spaceId: options.spaceId, accessToken: options.accessToken)
let syncableTypes =  SyncSpace.SyncableTypes.entriesOfContentType(withId: options.contentType)
client.sync(syncableTypes: syncableTypes) {(result: Result<SyncSpace, Error>) in
     switch result {
     case .success(let syncSpace):
     // handle success
     case .failure(let error):
    // handle error
     }
}
```

When I executed the above code I got below error message

`Message: When passing a sync token you can not pass any other parameters. If you want to sync only a specific type or content_type start a new sync with "initial"."`

**Comment by tomkowz** [comment]
@volkanbicer you're right! Let me check that.

**Comment by tomkowz** [comment]
Thanks for the report! It took a while but now this is fixed. I've created PR #310 with the fix.

**Pull request closed without merging**
