### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by leoneparise**
Update `venmo/DVR` to `1.3.2` and `AliSoftware/OHHTTPStubs` to `7.0.0`.

### CODE REVIEW

**Comment by mariobodemann** [comment]
Hey @leoneparise,

thanks for clarifying on #261, sadly I cannot merge this PR, since it is out of date with the base branch ...

**Comment by leoneparise** [comment]
@mariobodemann I updated from latest `master` branch.

**Comment by mariobodemann** [comment]
:thinking: Hmmm, I'm seeing a lot of these:

```
⚠️  /Users/travis/build/contentful/contentful.swift/Tests/ContentfulTests/PersistenceIntegrationTests.swift:30:29: 'archiveRootObject(_:toFile:)' was deprecated in tvOS 12.0: Use +archivedDataWithRootObject:requiringSecureCoding:error: instead
            NSKeyedArchiver.archiveRootObject(location as Any, toFile: "location")
                            ^
```

in https://travis-ci.org/contentful/contentful.swift/jobs/520886814

any idea what is going on there?

**Comment by manmal** [comment]
@leoneparise Thank you, this PR can be closed — OHHTTPStubs `8.0.0` and DVR `1.3.2` were updated in #268 which has been merged to master.

**Pull request closed without merging**
