### PR TITLE
Reuse date formatters

### PR DESCRIPTION
**Pull request by donnywals**
This pull request improves the SDK's performance by reusing date formatters instead of creating and updating them frequently.

### CODE REVIEW

**Comment by mgoudy91** [comment]
@mariuskatcontentful thoughts on this?

**Review by mariuskatcontentful — CHANGES_REQUESTED** [review]
Looks good but tests failing for some reason if you can fix those i can merge immediately

**Comment by donnywals** [comment]
@mariuskatcontentful should be good to go now :)

**Comment by mariuskatcontentful** [comment]
Merged

**Pull request merged**
