### PR TITLE
- Compilation fix for a case when project path contains spaces

### PR DESCRIPTION
**Pull request by anton-plebanovich**

### CODE REVIEW

**Comment by loudmouth** [comment]
Hi Anton,

Can you please provide some context as to what the goal of this PR is? What package manager are you using for instance? The swiftlint script for the SDK should not be executed if the SDK is a dependency on your project; were you seeing it being executed?

**Comment by anton-plebanovich** [comment]
Hi @loudmouth got error when tried to add `contentful.swift` via a Carthage and my project path contained space.

**Comment by anton-plebanovich** [comment]
@loudmouth If it recompiles from source build phase script is performed and build doesn't compile. I'm facing this issue right now while trying to build for Xcode 10.1. Could you possibly merge this one?

**Comment by loudmouth** [comment]
Hey @anton-plebanovich i can merge if you rebase on master...currently there are merge conflicts that make merging not possible

**Comment by anton-plebanovich** [comment]
Strange, I have no conflicts. Merged in `master` anyway so should be good now after CI finishes build.

**Comment by loudmouth** [comment]
@anton-plebanovich I just released [4.1.1](https://github.com/contentful/contentful.swift/releases/tag/4.1.1). 

Since this was only an issue with Carthage, there is no cocoapods release for this version.

**Comment by anton-plebanovich** [comment]
Great! Thanks!

**Pull request merged**
