### PR TITLE
Fix Framework search paths; extension only API

### LINKED ISSUE #100: Allow use in extensions
Can we have `APPLICATION_EXTENSION_API_ONLY = YES` set, so the SDK can be used in extensions? Currently we are getting a warning that this flag isn't set. When I set it manually it built fine, meaning the SDK isn't using any APIs that would be prohibited.

### PR DESCRIPTION
**Pull request by loudmouth**
Fixes #100 and #101

### CODE REVIEW

**Comment by loudmouth** [comment]
@brentleyjones would you be able to confirm that this PR solves both of your issues?

**Comment by brentleyjones** [comment]
@loudmouth Like I said https://github.com/contentful/contentful.swift/issues/101#issuecomment-317822070 I recommend that you setup submodules for the dependencies. Not strictly needed for these changes, since end users of the SDK don't need them setup this way, it will just make development/contribution easier.

These changes resolve both of my issues.

**Comment by loudmouth** [comment]
This also shaved ~2-3 minutes of the travis builds! 👏

**Comment by loudmouth** [comment]
@brentleyjones this merge  has had an unforeseen and unintended consequence. now when running tests with a different scheme configuration (i.e. changing from `DEBUG` to a configuration that I have defined for execution on a private travis build which collects information about api endpoint converage), dependencies such as object mapper cannot be found despite the fact that all build settings for the second configuration (in this case `API_Coverage`) are the same.

```
No such module `ObjectMapper`
```
I checked out ReactiveCocoa and noticed the same thing there...is this expected?

**Comment by brentleyjones** [comment]
@loudmouth For the `API_Coverage` configuration you are running into this issue: https://stackoverflow.com/questions/30884778/how-to-compile-a-project-with-app-and-library-in-the-same-workspace-with-differe

I don't agree with the fix there, and have been using a different method.

1. I have a single `.framework` in the `Frameworks` folder for each dependency, pulled from the built Mac version (since it's path is `Debug` instead of `Debug-iphonesimulator`). I make sure that the Location is set to "Relative to Build Products". When done right the resolved location under that dropdown becomes `ObjectMapper.framework` instead of some `../../` like path.
2. This will now correctly build the frameworks regardless of your configuration, but since your configuration `API_Coverage` doesn't exist in your dependencies Xcode will build whatever is the default for command line building, normally the `Release` configuration. So to solve this issue I have a build script that copies the built frameworks out of the `Release` directory into the configuration we are currently building:
```bash
#!/bin/bash

# Dependencies that don't have our custom configurations get build to Debug and Release build folders
if [ "$CONFIGURATION" != "Debug" ]; then
  echo "Copying frameworks from Release into the $CONFIGURATION product build directory."
  pushd "$BUILD_DIR/Release$EFFECTIVE_PLATFORM_NAME" > /dev/null

  for INFILE in ${!SCRIPT_INPUT_FILE_*}; do
    if [ $INFILE = "SCRIPT_INPUT_FILE_COUNT" ]; then
      break
    fi
    I=${!INFILE##${PROJECT_DIR}/}
    rsync -aL "$I" "$BUILT_PRODUCTS_DIR" # Can't use wildcard, if we have a Release config it would overrwite other frameworks
    echo "Copied $I"
  done

  popd > /dev/null
else
  echo "In $CONFIGURATION configuration. No manual framework copy."
fi
```

and the input strings are just the framework names:

copy-implicit-dependencies


Want me to create a PR that does all of this?

**Comment by brentleyjones** [comment]
https://stackoverflow.com/a/42883422/618470 might just work as well and is less maintenance 🤷‍♂️

**Comment by loudmouth** [comment]
🤔  hmmm...

it seems funny to re-add Framework search paths (but only for this one configuration) right after removing them. Nevertheless, I decided to give the later solution a try given it's simplicity and found that it works well. Of course, I've only added the framework search paths for this specific configuration which I don't expect other contributors to have to worry about. I will make sure to document this properly for whoever may pick up this project after me.

Thanks again for the information!

**Comment by brentleyjones** [comment]
@loudmouth Well, the search paths just have to not reference the Carthage Build folder. The one in that answer references the normal build folder output, so it's still better than before.

**Comment by loudmouth** [comment]
Thanks again @brentleyjones. Also just a heads up that in my next pr, your GH handle has been added to the Changelog ;-)

**Pull request merged**
