### PR TITLE
Swift 5 conversion

### PR DESCRIPTION
**Pull request by leoneparise**
This pull request converts the project to Swift 5 and fix all warning and deprecated code. It doesn't change the public API so it should be code compatible with previous versions.

### CODE REVIEW

**Comment by chriswunsch00** [comment]
When do you expect this to be merged ?

**Comment by Killectro** [comment]
Are there any updates on this? Would love to use it whenever it is! Thanks so much

**Comment by andrewcampoli** [comment]
Do you have any idea when this might be merged? Thanks!

**Comment by manmal** [comment]
Hi all, let me take over from here :) 
This pull request has just been superseded by #269 (because I can't edit this PR), which should be merged very soon.

Duplicate of #269

**Comment by leoneparise** [comment]
Thanks @manmal. I'm closing this PR.

**Pull request closed without merging**
