### PR TITLE
Bugfix/sync space paging

### PR DESCRIPTION
**Pull request by chrisozenne**
There is currently a bug in which the `sync()` function is called recursively using the newest result object, instead of the original `syncSpace` object. This results in the completion block being called with a space that only contains the entries from the last page in the sync process.

Example:
47 Entries to be synced
Page 1 = 37 entries
Page 2 = 10 entries
`syncSpace` should contain 47 entries, but instead only contains the last 10.

On line 564 a `syncSpace` variable is declared with the same name as the function parameter. That variable is mistakenly being passed into `self.sync(...)` instead of the original `syncSpace`.

Additionally...

Because of the above bug, the code above it which is intended to prevent multi-page syncing via the preview API is also broken as a result:

```
if !syncSpace.syncToken.isEmpty && host == Host.preview && syncSpace.hasMorePages == false {
    completion(Result.error(SDKError.previewAPIDoesNotSupportSync()))
    return nil
}
```

The `previewAPIDoesNotSupportSync` error is not thrown because the `syncSpace` being inspected is always the newest result, never the original `syncSpace`.

### CODE REVIEW

**Comment by mariobodemann** [comment]
Hello and thank you for your contribution.

Right now we are not able to support swift fully but we will come back to this PR once this situation changes.

Greetings,
Mario

**Comment by loudmouth** [comment]
LGTM. Saw that tests are passing too 🎉

**Comment by leoneparise** [comment]
@loudmouth Tests are passing but there was not tests that was checking sync pagination. I tried the code, it's working and much easier to understand than the current code. LGTM

**Comment by mariobodemann** [comment]
@leoneparise Would it make sense to add tests here then? On a quick glance I couln't find a test covering paging, and this would be a perfect candidate to add them.

What do you think?

**Comment by leoneparise** [comment]
@mariobodemann  I added this fix into my PR (https://github.com/contentful/contentful.swift/pull/261). You can close this PR now.

**Pull request closed without merging**
